In [1]:
import torch

Основная структура данных для `PyTorch` это  **тензоры** - многомерные матрицы.

In [5]:
torch.ones([3, 4, 2]) # 3 плоскости на 4 строчки на 2 столбца

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

Произвольный тензор можно создать из объекта `list`

In [8]:
x = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [14]:
print(' size(): {},\n shape : {}'.format(x.size(), x.shape)) 

 size(): torch.Size([2, 4]),
 shape : torch.Size([2, 4])


### Индексаци

In [16]:
x[0] # строка

tensor([1., 2., 3., 4.])

In [20]:
x[:,0] # столбец 

tensor([1., 5.])

In [22]:
x[0,0] # элемент

tensor(1.)

### Операции с тензорами

Операции над тензорами производятся поэлементно

In [24]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.]])

In [25]:
x ** 2

tensor([[ 1.,  4.,  9., 16.],
        [25., 36., 49., 64.]])

In [63]:
y = torch.Tensor([
    [11., 12., 13., 14.],
    [15., 16., 17., 18.]
])

In [30]:
y - x

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [34]:
 y > 14

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [35]:
mask = y > 14

In [37]:
x[mask]

tensor([5., 6., 7., 8.])

In [39]:
x[x>3]

tensor([4., 5., 6., 7., 8.])

# Копирование

In [40]:
x

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [41]:
y

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.]])

In [43]:
x = y
y[0, 0] = -100

In [44]:
x

tensor([[-100.,   12.,   13.,   14.],
        [  15.,   16.,   17.,   18.]])

In [45]:
y

tensor([[-100.,   12.,   13.,   14.],
        [  15.,   16.,   17.,   18.]])

Данное копирование является копированием по ссылке, на объект в памяти `x` начинает ссылаться еще и `y`

Для копированиея необходимо использовать метод `clone()`

In [60]:
x = torch.randn( 2, 4)

In [61]:
x

tensor([[-0.3305,  0.4010, -0.7529, -0.9881],
        [-1.0798, -0.8960, -0.1526, -1.3626]])

In [64]:
y

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.]])

In [66]:
y = x.clone()
y[0, 0] = 0

In [67]:
x

tensor([[-0.3305,  0.4010, -0.7529, -0.9881],
        [-1.0798, -0.8960, -0.1526, -1.3626]])

In [69]:
y

tensor([[ 0.0000,  0.4010, -0.7529, -0.9881],
        [-1.0798, -0.8960, -0.1526, -1.3626]])

# Типы данных

In [71]:
x.dtype 

torch.float32

In [73]:
x.double()

tensor([[-0.3305,  0.4010, -0.7529, -0.9881],
        [-1.0798, -0.8960, -0.1526, -1.3626]], dtype=torch.float64)

In [74]:
x.int()

tensor([[ 0,  0,  0,  0],
        [-1,  0,  0, -1]], dtype=torch.int32)

In [75]:
import numpy as np

In [76]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [77]:
x = torch.from_numpy(x)

In [79]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [80]:
x = x.numpy()

In [81]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# GPU

In [82]:
x = torch.rand([2, 3])
x

tensor([[0.3368, 0.4756, 0.3106],
        [0.4736, 0.0289, 0.6563]])

In [85]:
torch.cuda.is_available()

False

In [86]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [87]:
torch.device('cpu')

device(type='cpu')

In [92]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [93]:
x = x.to(device)